- name: create roboshop user
  ansible.builtin.user:
    name: roboshop
  
- name: Recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Download {{component}} application" 
  ansible.builtin.uri: 
    url : "curl -o /tmp/{{component}}.zip https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "Unarchive {{component}} application"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes