- name: disable old nodejs and enable nodejs
  ansible.builtin.shell: dnf module disable nodejs ; dnf module enable nodejs:18 

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app