# - name: Copying catalogue services
#   ansible.builtin.copy:
#     src: catalogue.service.j2
#     dest: /etc/systemd/system/catalogue.service

- name: "Copying {{component}} services"
  ansible.builtin.copy:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service.j2"

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes

  